if version > 800 || has('nvim')
source $HOME/.vim/autoload/plug.vim
source $HOME/.vim/plugins.vim
source $HOME/.vim/plugconf.vim
endif
source $HOME/.vim/base.vim
source $HOME/.vim/keymap.vim
source $HOME/.vim/optional.vim

augroup InitVI
autocmd!

""根据文件类型决定是否加载code.vim
autocmd FileType c,cpp,java,sh,python,go,javascript
    \ source $HOME/.vim/code.vim | let b:new_file = 1
""定义临时变量用于标记新建文件, 新建.c,.h,.sh,.java等文件时, 自动插入文件头
autocmd BufNewFile * if exists('b:new_file') | call SetTitle() | unlet b:new_file | endif

autocmd FileType markdown source $HOME/.vim/md-snippets.vim
""autocmd FileType c,cpp source $HOME/.vim/test.vim
if version > 800 || has('nvim')
""自动格式化c/c++ code
autocmd FileType c,cpp ClangFormatAutoEnable

endif
autocmd FileType cpp set dictionary=$HOME/.vim/.dict/dictcv.dict
""get correct comment highlighting about json
autocmd FileType json syntax match Comment +\/\/.\+$+
augroup END
