#!/usr/bin/env bash
###################################################
# Filename: mbk
# Author: aqshing
# Email: aqdebug.com aqdebug@gmail.com
# Brief: move file to file.bkp
# Created: 2020-10-29 12:09:18
# Changed: 2022-09-13 12:03:28
###################################################
# set -Exeuo pipefail

function mover() {
	if [ $# = 1 ]; then
		if [ "$1" = "--help" ]; then
			mv --help
		elif [[ "$1" =~ .bkp ]]; then
			mv "$1"{.bkp,} && echo "restore [$1.bkp] --> [$1]"
		elif [ -e "$1" ]; then
			mv "$1"{,.bkp} && echo "move [$1] --> [$1.bkp]"
		# else
		# 	echo "mv: cannot stat '$1': No such file or directory"
		fi
	else
		mv "$@"
	fi
}

unalias mv 2> /dev/null
mover  "$@"
exit  "$?"
