#!/usr/bin/env bash
###################################################
# Filename: type.sh
# Author: aqshing
# Email: aqdebug.com aqdebug@gmail.com
# Brief: 将zsh的type命令仿真为bash的type命令
# Created: 2022-07-14 16:27:38
# Changed: 2022-07-14 16:31:24
###################################################
# set -Exeuo pipefail

# 在本脚本中开启别名
shopt -s expand_aliases
# 加载别名
START_DIR=$(
    cd "$(dirname "$0")" || exit
    pwd
)
for shname in "$START_DIR"/*.sh; do
    # shellcheck source=/dev/null
    source "${shname}" >|/dev/null 2>&1
done

# 恢复原bash的type命令
unalias type
type "$@"
exit "$?"
